### ISSUE TITLE
ERROR: Service "messageq" uses an undefined network "cocoannotator"

### ISSUE THREAD

**Issue by AdanMora** [jsbroks/coco-annotator#177] opened 2019-04-05 09:35 UTC
Hi @jsbroks,

I have this issue with the last version with the building up:

`ERROR: Service "messageq" uses an undefined network "cocoannotator"`

**Comment by jsbroks** [comment] 2019-04-05 12:03
Did you do a git pull as well? A lot has changed from 0.9 to 0.10

**Comment by AdanMora** [comment] 2019-04-05 12:08
Yes it is already up to date, I'm doing a fresh restart of everything trying to find out the previous issue #172

**Comment by jsbroks** [comment] 2019-04-05 12:18
Try `docker-compose -f docker-compose.build.yml up`

**Comment by AdanMora** [comment] 2019-04-05 12:27
It works! You know the issue? The `docker-compose up` doesn't works at all.

**Comment by AdanMora** [comment] 2019-04-05 12:33
OFF TOPIC: Seems like there is a missing `import os`:

![image](https://user-images.githubusercontent.com/32461935/55627994-d40c9b00-57af-11e9-8619-dda942506b3e.png)

**Comment by jsbroks** [comment] 2019-04-05 13:22
No idea but I couldn't test the `docker-compose.yml` before release since it needs build images to run. I'll look into it later today.

I wont be able to fix the import until later today, so if you could put a quick PR, that would be appreciated.

**Comment by jsbroks** [comment] 2019-04-05 13:27
I forgot to add the network in the docker-compose file. Easy fix for both issues.

**Comment by AdanMora** [comment] 2019-04-05 13:29
I thought it was something like that, PR ready.

**Comment by jsbroks** [comment] 2019-04-05 13:30
I was able to fix the docker-compose, if you would like to try again

**Comment by AdanMora** [comment] 2019-04-05 13:43
I think is ready but you have to update the image on dockerhub, with `docker-compose -f docker-compose.build.yml up --build` works. Thanks!

**Comment by jsbroks** [comment] 2019-04-05 13:46
Give it about an hour, it automatically builds the images on each commit. You will need to us the latest images instead of stable as per usual

**Comment by AdanMora** [comment] 2019-04-05 13:50
Excellent! Just for the record, about the Issue #172, I have no idea what happened, I delete absolutely everything from docker, fresh restart, now it seems to work fine.

**Comment by jsbroks** [comment] 2019-04-05 13:55
I'm not sure either, I'll can close the issue and reopen it if we find a reproducible bug.

**Closed** 2019-04-06 14:57 UTC
