### ISSUE TITLE
Feature Request: Move segmentation from one category into another 

### ISSUE THREAD

**Issue by schwabse** [jsbroks/coco-annotator#217] opened 2019-06-20 13:50 UTC
Great piece of software! I really enjoy using it. 

If some user made a mistake, for example by segmenting a cat in the dog category of a particular dataset is it possible to transfer the false segmentation into another category of the same dataset? 

Thank you for the great work.

**Comment by jsbroks** [comment] 2019-06-20 18:39
Currently not possible. Duplicate of #111

**Closed** 2019-07-09 12:57 UTC
Labels: type: duplicate
